name: Deploy docs to GitHub Pages

on:
    push:
        branches:
            - '8.0'
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build:
        name: Build (symfony-tools/docs-builder)

        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v6

            -   name: "Set-up PHP"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.4
                    coverage: none

            -   name: Get composer cache directory
                id: composercache
                working-directory: _build
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('_build/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: "Install dependencies"
                working-directory: _build
                run: composer install --prefer-dist --no-progress

            -   name: "Build the docs"
                working-directory: _build
                run: php build.php

            -   name: "Setup Pages"
                uses: actions/configure-pages@v5

            -   name: "Upload build output"
                uses: actions/upload-pages-artifact@v3
                with:
                    path: _build/output

    deploy:
        name: Deploy to GitHub Pages

        needs: build

        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            -   name: "Deploy to GitHub Pages"
                id: deployment
                uses: actions/deploy-pages@v4
